main/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('product.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views.main_views import search, findus, cms_page, cms_product, cms_story
from .views.product_views import product_detail, edit_product, \
    product_activate, product_new, product_index
from .views.story_views import story_index, story_detail, edit_story, story_activate
from .views.brand_category_views import brand_index, load_subcategory, add_subcategory, \
    add_category, edit_subcategory
from .views.home_cms_views import home, home_image_carousel, home_body, home_list_highlight, \
    home_edit_highlight, delete_highlight, status_image_carousel
from .views.catalog_views import add_catalog, delete_catalog, pdf_view
from .views.about_views import about_company_edit, about_commitment_edit, about_designer_edit, \
    cms_designer_list, delete_designer, about_company, about_commitment, about_designer

urlpatterns = [
    path('', home, name='home'),
    path('search/', search, name='search'),
    path('products/', product_index, name='product_index'),
    path('products/<str:category>', product_index, name='product_category'),
    path('products/<str:category>/<str:subcategory>', product_index, name='product_subcategory'),
    path('about_us/', findus, name='about_us'),
    path('our_company/', about_company, name='about_company'),
    path('our_commitment/', about_commitment, name='about_commitment'),
    path('our_designer/', about_designer, name='about_designer'),
    path('cms/', cms_page, name='cms_page'),
    path('cms/product/', cms_product, name='cms_product'),
    path('cms/story/', cms_story, name='cms_story'),

    path('add_product/', edit_product, name='add_product'),
    path('products/detail/<int:id>', product_detail, name='product_detail'),
    path('edit_product/<int:id>', edit_product, name='product_edit'),
    path('update_status_product/<int:id>/<str:status>', product_activate, name='product_activate'),
    path('update_new_product/<int:id>/<str:status>', product_new, name='product_new'),

    path('blog/', story_index, name='stories'),
    path('add_story/', edit_story, name='add_story'),
    path('story_detail/<int:id>', story_detail, name='story_detail'),
    path('edit_story/<int:id>', edit_story, name='story_edit'),
    path('update_status_story/<int:id>/<str:status>', story_activate, name='story_activate'),

    path('add_brands/', brand_index, name='brand_index'),
    path('edit_brands/<int:id>', brand_index, name='edit_brand'),
    path('add_category/', add_category, name='category_index'),
    path('edit_category/<int:id>', add_category, name='edit_category'),
    path('add_subcategory/', add_subcategory, name='subcategory_index'),
    path('edit_subcategory/<int:id>', edit_subcategory, name='edit_subcategory'),
    path('ajax/load-subcategory/', load_subcategory, name='ajax_load_subcategory'),

    path('cms/home/edit/image_carousel', home_image_carousel, name='home_image_carousel'),
    path('cms/home/edit/image_carousel/change_status/<int:id>/<str:status>', status_image_carousel,
         name='edit_status_image_carousel'),
    path('cms/home/edit/body', home_body, name='home_body'),
    path('cms/home/edit/list_highlight', home_list_highlight, name='home_list_highlights'),
    path('cms/home/edit/add_highlight', home_edit_highlight, name='add_highlights'),
    path('cms/home/edit/edit_highlight/<int:id>', home_edit_highlight, name='edit_highlights'),
    path('cms/home/edit/delete_highlight/<int:id>', delete_highlight, name='delete_highlights'),

    path('cms/about/edit/about_company', about_company_edit, name='edit_about_company'),
    path('cms/about/edit/about_commitment', about_commitment_edit, name='edit_about_commitment'),
    path('cms/about/designer_list', cms_designer_list, name='cms_designer_list'),
    path('cms/about/add_designer', about_designer_edit, name='add_designer'),
    path('cms/about/edit_designer/<int:id>', about_designer_edit, name='edit_designer'),
    path('cms/about/remove_designer/<int:id>', delete_designer, name='delete_designer'),

    path('cms/add/catalog/', add_catalog, name='add_catalog'),
    path('cms/edit/catalog/<int:id>', add_catalog, name='edit_catalog'),
    path('cms/delete/catalog/<int:id>', delete_catalog, name='delete_catalog'),
    path('show_pdf/<str:title>', pdf_view, name='pdf_view'),
]

product/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models


class Brand(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=20)
    image = models.ImageField(upload_to='static/uploads/category_image', null=True)

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    name = models.CharField(max_length=20)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='subcategories')

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=20)
    code = models.CharField(max_length=20)
    dimension = models.CharField(max_length=50)
    features = models.CharField(max_length=255)
    material = models.CharField(max_length=50)
    color = models.CharField(max_length=50)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    new = models.BooleanField(default=False)
    home_carousel = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.SET_NULL, null=True)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class Image(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name='product_image')
    image = models.ImageField(upload_to='static/uploads/products', null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    order = models.IntegerField()

    class Meta:
        ordering = ['order']


class Stories(models.Model):
    title = models.CharField(max_length=100)
    snippet = models.TextField()
    body = RichTextUploadingField()
    story_date = models.DateField()
    date_added = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    title_image = models.ImageField(upload_to='static/uploads/stories')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class HomePage(models.Model):
    text = RichTextUploadingField()


class HomePageHighlight(models.Model):
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=100)
    list_product = models.CharField(max_length=255)


class Catalog(models.Model):
    def validate_file_extension(value):
        if value.file.content_type != 'application/pdf':
            raise ValidationError(u'Please insert PDF file')

    title = models.CharField(max_length=100)
    file = models.FileField(upload_to='static/uploads/catalog',
                            validators=[validate_file_extension])


class AboutCompany(models.Model):
    image_header = models.ImageField(upload_to='static/uploads/about_company_header')
    text = RichTextUploadingField()


class AboutCommitment(models.Model):
    image_header = models.ImageField(upload_to='static/uploads/about_commitment_header')
    text = RichTextUploadingField()
    image_footer = models.ImageField(upload_to='static/uploads/about_commitment_footer')
    footer_text = models.TextField()


class AboutDesigner(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='static/uploads/designers')

product/views/about_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect, get_object_or_404

from product.forms import AboutCompanyForm, AboutCommitmentForm, AboutDesignerForm
from product.models import AboutCompany, AboutCommitment, AboutDesigner


def about_company(request):
    company = AboutCompany.objects.first()
    return render(request, 'about_company_index.html', {'company': company})


def about_commitment(request):
    commitment = AboutCommitment.objects.first()
    return render(request, 'about_commitment_index.html', {'commitment': commitment})


def about_designer(request):
    designers = AboutDesigner.objects.all()
    return render(request, 'about_designer_index.html', {'designers': designers})


# --------------------------------------- THIS CODE BELOW IS FOR CMS -----------------------------------------

@login_required
@user_passes_test(lambda u: u.is_superuser)
def about_company_edit(request):
    about_company_body = AboutCompany.objects.first()
    if request.method == 'POST':
        about_company_form = AboutCompanyForm(request.POST, request.FILES, instance=about_company_body)
        if about_company_form.is_valid():
            about_company_form.save()
            messages.success(request, 'Successfully edit about company page')
            return redirect('edit_about_company')
    else:
        about_company_form = AboutCompanyForm(instance=about_company_body)
    return render(request, 'cms/about_company.html', {'nav': 'home', 'form': about_company_form})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def about_commitment_edit(request):
    about_commitment_body = AboutCommitment.objects.first()
    if request.method == 'POST':
        about_commitment_form = AboutCommitmentForm(request.POST, request.FILES, instance=about_commitment_body)
        if about_commitment_form.is_valid():
            about_commitment_form.save()
            messages.success(request, 'Successfully edit about commitment page')
            return redirect('edit_about_commitment')
    else:
        about_commitment_form = AboutCommitmentForm(instance=about_commitment_body)
    return render(request, 'cms/about_commitment.html', {'nav': 'home', 'form': about_commitment_form})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def cms_designer_list(request):
    designer_list = AboutDesigner.objects.all().order_by('id')
    return render(request, 'cms/about_designer.html', {'nav': 'home', 'designers': designer_list})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def about_designer_edit(request, id=None):
    if id is not None:
        designer_instance = get_object_or_404(AboutDesigner, pk=id)
        msg = 'Successfully edit designer'
        title = 'Edit'
    else:
        designer_instance = AboutDesigner()
        msg = 'Successfully add designer'
        title = 'Add New'

    if request.method == 'POST':
        designer_form = AboutDesignerForm(request.POST, request.FILES, instance=designer_instance)
        if designer_form.is_valid():
            designer_form.save()
            messages.success(request, msg)
            return redirect('cms_designer_list')
    else:
        designer_form = AboutDesignerForm(instance=designer_instance)
    return render(request, 'cms/add_designer.html', {'nav': 'home', 'form': designer_form, 'title': title})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def delete_designer(request, id):
    AboutDesigner.objects.get(id=id).delete()
    messages.success(request, 'Successfully delete designer')
    return redirect('cms_designer_list')

product/views/brand_category_views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages

from product.models import Brand, SubCategory, Category
from ..forms import BrandForm, CategoryForm, SubcategoryForm


@login_required
@user_passes_test(lambda u: u.is_superuser)
def brand_index(request, id=None):
    brand = Brand.objects.all().order_by('name')

    if id is not None:
        brand_instance = Brand.objects.get(id=id)
        msg = 'Successfully edit brand'
        title = 'Edit'
    else:
        brand_instance = Brand()
        msg = 'Successfully add brand'
        title = 'Add new'

    if request.method == 'POST':
        form = BrandForm(request.POST, instance=brand_instance)
        if form.is_valid():
            form.save()
            messages.success(request, msg)
            return redirect('brand_index')
    else:
        form = BrandForm(instance=brand_instance)

    return render(request, 'cms/brand_page.html', {'brands': brand, 'form': form, 'title': title})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def add_category(request, id=None):
    category = Category.objects.all().order_by('name')

    if id is not None:
        category_instance = Category.objects.get(id=id)
        msg = 'Successfully edit category'
        title = 'Edit'
    else:
        category_instance = Category()
        msg = 'Successfully add category'
        title = 'Add new'

    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=category_instance)
        if form.is_valid():
            form.save()
            messages.success(request, msg)
            return redirect('category_index')
    else:
        form = CategoryForm(instance=category_instance)

    return render(request, 'cms/add_category.html', {'categories': category, 'form': form, 'title': title})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def add_subcategory(request, id=None):
    categories = []
    list_category = Category.objects.all().order_by('name')
    for category in list_category:
        list_subcategory = SubCategory.objects.filter(category_id=category.id).order_by('name')
        if not list_subcategory:
            categories.append(dict(category=category.name, subcategory=''))
        for subcategory in list_subcategory:
            categories.append(dict(id=subcategory.id, category=category.name, subcategory=subcategory.name))

    if id is not None:
        subcategory_instance = SubCategory.objects.get(id=id)
        msg = 'Successfully edit subcategory'
        title = 'Edit'
    else:
        subcategory_instance = SubCategory()
        msg = 'Successfully add subcategory'
        title = 'Add new'

    if request.method == 'POST':
        subcategory_form = SubcategoryForm(request.POST, instance=subcategory_instance)
        if subcategory_form.is_valid():
            subcategory_form.save()
            messages.success(request, msg)
            return redirect('subcategory_index')
    else:
        subcategory_form = SubcategoryForm(instance=subcategory_instance)

    return render(request, 'cms/add_subcategory.html',
                  {'subcategories': categories,
                   'subcategory_form': subcategory_form,
                   'title': title})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def edit_subcategory(request, id):
    subcategory_instance = get_object_or_404(SubCategory, pk=id)

    if request.method == 'POST':
        subcategory_form = SubcategoryForm(request.POST, instance=subcategory_instance)
        if subcategory_form.is_valid():
            subcategory_form.save()
            messages.success(request, 'Successfully edit subcategory')
            return redirect('subcategory_index')
    else:
        subcategory_form = SubcategoryForm(instance=subcategory_instance)

    return render(request, 'cms/edit_subcategory.html',
                  {'subcategory_form': subcategory_form})


def load_subcategory(request):
    category_id = request.GET.get('category')
    subcategory = SubCategory.objects.filter(category_id=category_id).order_by('name')
    return render(request, 'cms/subcategory_dropdown_list.html', {'subcategories': subcategory})

product/templates/cms/about_company.html
{% extends 'cms/index.html' %}

{% load crispy_forms_tags %}

{% block content %}
    {% if messages %}
        <div class="alert alert-success" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}

    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h1>About Company Page</h1>
            </div>
        </div>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-4 mb-0">
                    {{ form.image_header|as_crispy_field}}
                    {{ form.media }}
                    {{ form.text|as_crispy_field }}
                </div>
            </div>

            <button type="submit" class="btn btn-primary">Save</button>
            <a href="javascript:history.back()" class="btn btn-secondary" role="button">Cancel</a>
        </form>
    </div>
{% endblock %}

product/templates/cms/about_designer.html
{% extends 'cms/index.html' %}

{% block content %}
    {% if messages %}
        <div class="alert alert-success" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}

    <div class="container-fluid">
        <div class="row">
            <h1>Designer</h1>
        </div>
        <div class="row add-btn">
            <a href="{% url 'add_designer' %}" class="btn btn-primary" role="button">Add Designer</a>
        </div>
        <br>
        <div class="row">
            <div class="table-responsive">
                <table id="designerTable" class="table table-bordred table-striped">
                    <thead>
                        <th>No.</th>
                        <th>Name</th>
                        <th style="text-align: center">Edit</th>
                        <th style="text-align: center">Delete</th>
                    </thead>
                    <tbody>
                        {% for d in designers %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ d.name }}</td>
                                <td style="text-align: center"><a href="{% url 'edit_designer' d.id %}"><button class="btn-table"><i class="fas fa-edit"></i></button></a></td>
                                <td style="text-align: center"><a href="{% url 'delete_designer' d.id %}"><button class="btn-table"><i class="fas fa-trash-alt"></i></button></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $('#designerTable').DataTable( {
                "pagingType": "full_numbers"
            } );
        });
    </script>
{% endblock %}

product/templates/cms/add_catalog.html
{% extends 'cms/index.html' %}

{% load crispy_forms_tags %}
{% block content %}
    {% if messages %}
        <div class="alert alert-success" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}

    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h1>Catalog</h1>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col">
                <div class="table-responsive">
                    <table id="catalogTable" class="table table-bordred table-striped">
                        <thead>
                            <th>No.</th>
                            <th>Name</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </thead>
                        <tbody>
                            {% for catalog in catalogs %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ catalog.title }}</td>
                                    <td><a href="{% url 'edit_catalog' catalog.id %}"><button class="btn-table"><i class="fas fa-edit"></i></button></a> </td>
                                    <td><a href="{% url 'delete_catalog' catalog.id %}"><button class="btn-table"><i class="fas fa-trash-alt"></i></button></a> </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col">
                <h2>{{ title }} catalog</h2>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-2 mb-0">
                            {{ form.title|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6 mb-0">
                            {{ form.file|as_crispy_field }}
                            {{ form.errors }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="javascript:history.back()" class="btn btn-secondary" role="button">Cancel</a>
                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $('#catalogTable').DataTable( {
                "pagingType": "full_numbers"
            } );
        } );
    </script>
{% endblock %}

product/templates/cms/add_designer.html
{% extends 'cms/index.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid">
    <div class="row"><br></div>
    <div class="row">
        <div class="col">
            <h1>{{ title }} Designer</h1>
        </div>
    </div>
    <hr>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-4 mb-0">
            {{ form.name|as_crispy_field }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4 mb-0">
              {{ form.image|as_crispy_field }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4 mb-0">
            {{ form.description|as_crispy_field }}
          </div>
        </div>

        <button type="submit" class="btn btn-primary">Save</button>
        <a href="javascript:history.back()" class="btn btn-secondary" role="button">Cancel</a>
    </form>
</div>

{% endblock %}

product/templates/cms/add_story.html
{% extends 'cms/index.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid">
    <div class="row"><br></div>
    <div class="row">
        <div class="col">
            <h1>{{ title }} Story</h1>
        </div>
    </div>
    <hr>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-4 mb-0">
            {{ form.title|as_crispy_field }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4 mb-0">
              {{ form.story_date|as_crispy_field }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4 mb-0">
            {{ form.title_image|as_crispy_field }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4 mb-0">
            {{ form.snippet|as_crispy_field }}
          </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
                {{ form.media }}
                {{ form.body|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4 mb-0">
            {{ form.is_active|as_crispy_field }}
          </div>
        </div>

        <button type="submit" class="btn btn-primary">Save</button>
        <a href="javascript:history.back()" class="btn btn-secondary" role="button">Cancel</a>
    </form>
</div>

<script>
  $(function () {
    $("#id_story_date").datepicker({
      format:'yyyy-mm-dd',
    });
  });
</script>
{% endblock %}

product/templates/cms/add_subcategory.html
{% extends 'cms/index.html' %}

{% load crispy_forms_tags %}
{% block content %}
    {% if messages %}
        <div class="alert alert-success" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}

    <div class="container-fluid">
        <div class="row"><br></div>
        <div class="row">
            <div class="col">
                <h1>Sub Category</h1>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col">
                <div class="table-responsive">
                    <table id="subcategoryTable" class="table table-bordred table-striped">
                        <thead>
                            <th>No.</th>
                            <th>Category</th>
                            <th>Sub Category</th>
                            <th>Edit</th>
                        </thead>
                        <tbody>
                            {% for subcategory in subcategories %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ subcategory.category }}</td>
                                    <td>{{ subcategory.subcategory}}</td>
                                    {% if subcategory.subcategory %}
                                        <td><a href="{% url 'edit_subcategory' subcategory.id %}"><button class="btn-table"><i class="fas fa-edit"></i></button></a> </td>
                                    {% else %}
                                        <td></td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col">
                <h2>Add subcategory</h2>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-3 mb-0">
                            {{ subcategory_form.category|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-3 mb-0">
                            {{ subcategory_form.name|as_crispy_field }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="javascript:history.back()" class="btn btn-secondary" role="button">Cancel</a>
                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $('#subcategoryTable').DataTable( {
                "pagingType": "full_numbers"
            } );
        } );
    </script>
{% endblock %}

product/templates/cms/brand_page.html
{% extends 'cms/index.html' %}

{% load crispy_forms_tags %}
{% block content %}
    {% if messages %}
        <div class="alert alert-success" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}

    <div class="container-fluid">
        <div class="row"><br></div>
        <div class="row">
            <div class="col">
                <h1>Brands</h1>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col">
                <div class="table-responsive">
                    <table id="brandTable" class="table table-bordred table-striped">
                        <thead>
                            <th>No.</th>
                            <th>Name</th>
                            <th>Edit</th>
                        </thead>
                        <tbody>
                            {% for brand in brands %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ brand }}</td>
                                    <td><a href="{% url 'edit_brand' brand.id %}"><button class="btn-table"><i class="fas fa-edit"></i></button></a> </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col">
                <h2>{{ title }} brand</h2>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-1 mb-0">
                            {{ form.name|as_crispy_field }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="javascript:history.back()" class="btn btn-secondary" role="button">Cancel</a>
                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $('#brandTable').DataTable( {
                "pagingType": "full_numbers"
            } );
        } );
    </script>
{% endblock %}

product/templates/cms/home_add_highlight.html
{% extends 'cms/index.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid">
    <div class="row"><br></div>
    <div class="row">
        <div class="col">
            <h1>{{ title }} Highlight</h1>
        </div>
    </div>
    <hr>
    <form method="post" id=productForm data-subcategory-url="{% url 'ajax_load_subcategory' %}" enctype="multipart/form-data" style="padding-bottom: 20px">
      {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-4 mb-0">
            {{ form.title|as_crispy_field }}
          </div>
          <div class="form-group col-md-4 mb-0">
            {{ form.sub_title|as_crispy_field }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4 mb-0">
            {{ form.list_product|as_crispy_field }}
          </div>
        </div>
        {{ form.errors }}
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="javascript:history.back()" class="btn btn-secondary" role="button">Cancel</a>
    </form>
</div>
{% endblock %}